go install github.com/cweill/gotests/gotests@v1.6.0
go install github.com/fatih/gomodifytags@v1.16.0
go install github.com/josharian/impl@v1.1.0
go install github.com/haya14busa/goplay/cmd/goplay@v1.0.0
go install github.com/go-delve/delve/cmd/dlv@latest
go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.50.1
go install golang.org/x/tools/gopls@latest
go install github.com/cosmtrek/air@latest
go install github.com/davidrjenni/reftools/cmd/fillstruct@v0.0.0-20210213085015-40322ffdc2e4
