version: "3"
services:
  go:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - ../:/src
    ports:
      - 80:80
      - 443:443
    tty: true
    env_file:
      - ../.env
